### ISSUE TITLE
programmatic usage

### ISSUE THREAD

**Issue by Bingo821227** [digitalkaoz/php-ipfs-api#6]
php-ipfs-api is introduced through autoload.php

test.php Code:

```
//$driver = $container[IPFS\Driver\Cli::class];
$driver = $container[IPFS\Driver\Http::class];
$client = new IPFS\Client($driver);
$response = $client->execute((new \IPFS\Api\Basics())->version());
var_dump($response);
```

error:

`Fatal error: Uncaught TypeError: Argument 1 passed to IPFS\Client::__construct() must implement interface IPFS\Driver\Driver, null given, called in /php/phalapi/public/1.php on line 12 and defined in /php/phalapi/vendor/ipfs/php-client/src/Client.php:26 Stack trace: #0 /php/phalapi/public/1.php(12): IPFS\Client->__construct(NULL) #1 {main} thrown in /php/phalapi/vendor/ipfs/php-client/src/Client.php on line 26`

**Comment by digitalkaoz** [comment]
try it like this:

you probably didnt imported the Pimple DIC:
see https://github.com/digitalkaoz/php-ipfs-api/blob/master/src/Container/ServiceProvider.php#L96 how to create the CLI Client by hand


```php
// cli driver
$driver = new \IPFS\Driver\Cli(new Process([]), new AnnotationReader(
                new \Doctrine\Common\Annotations\AnnotationReader(),
                \phpDocumentor\Reflection\DocBlockFactory::createInstance()
            ), getenv('IPFS_BINARY') ?: 'ipfs');

$client = new \IPFS\Client($driver);
$response = $client->execute((new \IPFS\Api\Basics())->version());
var_dump($response);
```

i strongly advice to use [Pimple](https://pimple.symfony.com/)

then it would be this easy:

```php
use Pimple\Container;  

//container
$container = new Container();
$container->register(new \IPFS\Container\ServiceProvider());

// setup api client
$driver = $container[\IPFS\Driver\Cli::class];
//$driver = $container[\IPFS\Driver\Http::class];
$client = new \IPFS\Client($driver);

//use it
$response = $client->execute((new \IPFS\Api\Basics())->version());
var_dump($response);
```

**Comment by Bingo821227** [comment]
Thank you very much for solving my problem. The epidemic is serious
recently. I hope everything is OK!
